//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PhoneSecurityStepLib.aspPhone {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ASPPhoneX2Soap", Namespace="https://webservice.aspPhone.com/aspPhonex2.asmx")]
    public partial class ASPPhoneX2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SimpleWAPPushOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSimpleTextPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTextPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUnicodePhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCreditsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOriginatorUnlockCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnlockOriginatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckOriginatorAuthorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTokenPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback InquireDeliveryNotificationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RedeemVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVoucherTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusCodeDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ASPPhoneX2() {
            this.Url = global::PhoneSecurityStepLib.Properties.Settings.Default.PhoneSecurityStepLib_aspPhone_ASPPhoneX2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SimpleWAPPushCompletedEventHandler SimpleWAPPushCompleted;
        
        /// <remarks/>
        public event SendSimpleTextPhoneCompletedEventHandler SendSimpleTextPhoneCompleted;
        
        /// <remarks/>
        public event SendTextPhoneCompletedEventHandler SendTextPhoneCompleted;
        
        /// <remarks/>
        public event SendUnicodePhoneCompletedEventHandler SendUnicodePhoneCompleted;
        
        /// <remarks/>
        public event CheckCreditsCompletedEventHandler CheckCreditsCompleted;
        
        /// <remarks/>
        public event SendOriginatorUnlockCodeCompletedEventHandler SendOriginatorUnlockCodeCompleted;
        
        /// <remarks/>
        public event UnlockOriginatorCompletedEventHandler UnlockOriginatorCompleted;
        
        /// <remarks/>
        public event CheckOriginatorAuthorizationCompletedEventHandler CheckOriginatorAuthorizationCompleted;
        
        /// <remarks/>
        public event VerifyTokenCompletedEventHandler VerifyTokenCompleted;
        
        /// <remarks/>
        public event SendTokenPhoneCompletedEventHandler SendTokenPhoneCompleted;
        
        /// <remarks/>
        public event InquireDeliveryNotificationsCompletedEventHandler InquireDeliveryNotificationsCompleted;
        
        /// <remarks/>
        public event RedeemVoucherCompletedEventHandler RedeemVoucherCompleted;
        
        /// <remarks/>
        public event CreateVoucherCompletedEventHandler CreateVoucherCompleted;
        
        /// <remarks/>
        public event GetVoucherTransactionsCompletedEventHandler GetVoucherTransactionsCompleted;
        
        /// <remarks/>
        public event GetStatusCodeDescriptionCompletedEventHandler GetStatusCodeDescriptionCompleted;
        
        /// <remarks/>
        public event VersionInfoCompletedEventHandler VersionInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/SimpleWAPPush", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SimpleWAPPush(string UserKey, string Password, string Recipients, string Originator, string WapDescription, string WapURL, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            object[] results = this.Invoke("SimpleWAPPush", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        WapDescription,
                        WapURL,
                        DeferredDeliveryTime,
                        FlashingPhone,
                        TimeZone,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SimpleWAPPushAsync(string UserKey, string Password, string Recipients, string Originator, string WapDescription, string WapURL, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            this.SimpleWAPPushAsync(UserKey, Password, Recipients, Originator, WapDescription, WapURL, DeferredDeliveryTime, FlashingPhone, TimeZone, URLBufferedMessageNotification, URLDeliveryNotification, URLNonDeliveryNotification, AffiliateId, null);
        }
        
        /// <remarks/>
        public void SimpleWAPPushAsync(string UserKey, string Password, string Recipients, string Originator, string WapDescription, string WapURL, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId, object userState) {
            if ((this.SimpleWAPPushOperationCompleted == null)) {
                this.SimpleWAPPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimpleWAPPushOperationCompleted);
            }
            this.InvokeAsync("SimpleWAPPush", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        WapDescription,
                        WapURL,
                        DeferredDeliveryTime,
                        FlashingPhone,
                        TimeZone,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId}, this.SimpleWAPPushOperationCompleted, userState);
        }
        
        private void OnSimpleWAPPushOperationCompleted(object arg) {
            if ((this.SimpleWAPPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimpleWAPPushCompleted(this, new SimpleWAPPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/SendSimpleTextPhone", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSimpleTextPhone(string UserKey, string Password, string Recipients, string Originator, string MessageText) {
            object[] results = this.Invoke("SendSimpleTextPhone", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        MessageText});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSimpleTextPhoneAsync(string UserKey, string Password, string Recipients, string Originator, string MessageText) {
            this.SendSimpleTextPhoneAsync(UserKey, Password, Recipients, Originator, MessageText, null);
        }
        
        /// <remarks/>
        public void SendSimpleTextPhoneAsync(string UserKey, string Password, string Recipients, string Originator, string MessageText, object userState) {
            if ((this.SendSimpleTextPhoneOperationCompleted == null)) {
                this.SendSimpleTextPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSimpleTextPhoneOperationCompleted);
            }
            this.InvokeAsync("SendSimpleTextPhone", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        MessageText}, this.SendSimpleTextPhoneOperationCompleted, userState);
        }
        
        private void OnSendSimpleTextPhoneOperationCompleted(object arg) {
            if ((this.SendSimpleTextPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSimpleTextPhoneCompleted(this, new SendSimpleTextPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/SendTextPhone", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTextPhone(string UserKey, string Password, string Recipients, string Originator, string MessageText, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            object[] results = this.Invoke("SendTextPhone", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        MessageText,
                        DeferredDeliveryTime,
                        FlashingPhone,
                        TimeZone,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTextPhoneAsync(string UserKey, string Password, string Recipients, string Originator, string MessageText, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            this.SendTextPhoneAsync(UserKey, Password, Recipients, Originator, MessageText, DeferredDeliveryTime, FlashingPhone, TimeZone, URLBufferedMessageNotification, URLDeliveryNotification, URLNonDeliveryNotification, AffiliateId, null);
        }
        
        /// <remarks/>
        public void SendTextPhoneAsync(string UserKey, string Password, string Recipients, string Originator, string MessageText, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId, object userState) {
            if ((this.SendTextPhoneOperationCompleted == null)) {
                this.SendTextPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTextPhoneOperationCompleted);
            }
            this.InvokeAsync("SendTextPhone", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        MessageText,
                        DeferredDeliveryTime,
                        FlashingPhone,
                        TimeZone,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId}, this.SendTextPhoneOperationCompleted, userState);
        }
        
        private void OnSendTextPhoneOperationCompleted(object arg) {
            if ((this.SendTextPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTextPhoneCompleted(this, new SendTextPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/SendUnicodePhone", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendUnicodePhone(string UserKey, string Password, string Recipients, string Originator, string MessageText, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            object[] results = this.Invoke("SendUnicodePhone", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        MessageText,
                        DeferredDeliveryTime,
                        FlashingPhone,
                        TimeZone,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendUnicodePhoneAsync(string UserKey, string Password, string Recipients, string Originator, string MessageText, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            this.SendUnicodePhoneAsync(UserKey, Password, Recipients, Originator, MessageText, DeferredDeliveryTime, FlashingPhone, TimeZone, URLBufferedMessageNotification, URLDeliveryNotification, URLNonDeliveryNotification, AffiliateId, null);
        }
        
        /// <remarks/>
        public void SendUnicodePhoneAsync(string UserKey, string Password, string Recipients, string Originator, string MessageText, string DeferredDeliveryTime, string FlashingPhone, string TimeZone, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId, object userState) {
            if ((this.SendUnicodePhoneOperationCompleted == null)) {
                this.SendUnicodePhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUnicodePhoneOperationCompleted);
            }
            this.InvokeAsync("SendUnicodePhone", new object[] {
                        UserKey,
                        Password,
                        Recipients,
                        Originator,
                        MessageText,
                        DeferredDeliveryTime,
                        FlashingPhone,
                        TimeZone,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId}, this.SendUnicodePhoneOperationCompleted, userState);
        }
        
        private void OnSendUnicodePhoneOperationCompleted(object arg) {
            if ((this.SendUnicodePhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUnicodePhoneCompleted(this, new SendUnicodePhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/CheckCredits", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckCredits(string UserKey, string Password) {
            object[] results = this.Invoke("CheckCredits", new object[] {
                        UserKey,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCreditsAsync(string UserKey, string Password) {
            this.CheckCreditsAsync(UserKey, Password, null);
        }
        
        /// <remarks/>
        public void CheckCreditsAsync(string UserKey, string Password, object userState) {
            if ((this.CheckCreditsOperationCompleted == null)) {
                this.CheckCreditsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCreditsOperationCompleted);
            }
            this.InvokeAsync("CheckCredits", new object[] {
                        UserKey,
                        Password}, this.CheckCreditsOperationCompleted, userState);
        }
        
        private void OnCheckCreditsOperationCompleted(object arg) {
            if ((this.CheckCreditsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCreditsCompleted(this, new CheckCreditsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/SendOriginatorUnlockCode", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOriginatorUnlockCode(string UserKey, string Password, string Originator) {
            object[] results = this.Invoke("SendOriginatorUnlockCode", new object[] {
                        UserKey,
                        Password,
                        Originator});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOriginatorUnlockCodeAsync(string UserKey, string Password, string Originator) {
            this.SendOriginatorUnlockCodeAsync(UserKey, Password, Originator, null);
        }
        
        /// <remarks/>
        public void SendOriginatorUnlockCodeAsync(string UserKey, string Password, string Originator, object userState) {
            if ((this.SendOriginatorUnlockCodeOperationCompleted == null)) {
                this.SendOriginatorUnlockCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOriginatorUnlockCodeOperationCompleted);
            }
            this.InvokeAsync("SendOriginatorUnlockCode", new object[] {
                        UserKey,
                        Password,
                        Originator}, this.SendOriginatorUnlockCodeOperationCompleted, userState);
        }
        
        private void OnSendOriginatorUnlockCodeOperationCompleted(object arg) {
            if ((this.SendOriginatorUnlockCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOriginatorUnlockCodeCompleted(this, new SendOriginatorUnlockCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/UnlockOriginator", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UnlockOriginator(string UserKey, string Password, string Originator, string OriginatorUnlockCode, string AffiliateId) {
            object[] results = this.Invoke("UnlockOriginator", new object[] {
                        UserKey,
                        Password,
                        Originator,
                        OriginatorUnlockCode,
                        AffiliateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UnlockOriginatorAsync(string UserKey, string Password, string Originator, string OriginatorUnlockCode, string AffiliateId) {
            this.UnlockOriginatorAsync(UserKey, Password, Originator, OriginatorUnlockCode, AffiliateId, null);
        }
        
        /// <remarks/>
        public void UnlockOriginatorAsync(string UserKey, string Password, string Originator, string OriginatorUnlockCode, string AffiliateId, object userState) {
            if ((this.UnlockOriginatorOperationCompleted == null)) {
                this.UnlockOriginatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnlockOriginatorOperationCompleted);
            }
            this.InvokeAsync("UnlockOriginator", new object[] {
                        UserKey,
                        Password,
                        Originator,
                        OriginatorUnlockCode,
                        AffiliateId}, this.UnlockOriginatorOperationCompleted, userState);
        }
        
        private void OnUnlockOriginatorOperationCompleted(object arg) {
            if ((this.UnlockOriginatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnlockOriginatorCompleted(this, new UnlockOriginatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/CheckOriginatorAuthorization", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckOriginatorAuthorization(string UserKey, string Password, string Originator) {
            object[] results = this.Invoke("CheckOriginatorAuthorization", new object[] {
                        UserKey,
                        Password,
                        Originator});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckOriginatorAuthorizationAsync(string UserKey, string Password, string Originator) {
            this.CheckOriginatorAuthorizationAsync(UserKey, Password, Originator, null);
        }
        
        /// <remarks/>
        public void CheckOriginatorAuthorizationAsync(string UserKey, string Password, string Originator, object userState) {
            if ((this.CheckOriginatorAuthorizationOperationCompleted == null)) {
                this.CheckOriginatorAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOriginatorAuthorizationOperationCompleted);
            }
            this.InvokeAsync("CheckOriginatorAuthorization", new object[] {
                        UserKey,
                        Password,
                        Originator}, this.CheckOriginatorAuthorizationOperationCompleted, userState);
        }
        
        private void OnCheckOriginatorAuthorizationOperationCompleted(object arg) {
            if ((this.CheckOriginatorAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckOriginatorAuthorizationCompleted(this, new CheckOriginatorAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/VerifyToken", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerifyToken(string UserKey, string Password, string PhoneNumber, string TokenReference, string VerificationCode) {
            object[] results = this.Invoke("VerifyToken", new object[] {
                        UserKey,
                        Password,
                        PhoneNumber,
                        TokenReference,
                        VerificationCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyTokenAsync(string UserKey, string Password, string PhoneNumber, string TokenReference, string VerificationCode) {
            this.VerifyTokenAsync(UserKey, Password, PhoneNumber, TokenReference, VerificationCode, null);
        }
        
        /// <remarks/>
        public void VerifyTokenAsync(string UserKey, string Password, string PhoneNumber, string TokenReference, string VerificationCode, object userState) {
            if ((this.VerifyTokenOperationCompleted == null)) {
                this.VerifyTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyTokenOperationCompleted);
            }
            this.InvokeAsync("VerifyToken", new object[] {
                        UserKey,
                        Password,
                        PhoneNumber,
                        TokenReference,
                        VerificationCode}, this.VerifyTokenOperationCompleted, userState);
        }
        
        private void OnVerifyTokenOperationCompleted(object arg) {
            if ((this.VerifyTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyTokenCompleted(this, new VerifyTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/SendTokenPhone", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTokenPhone(string UserKey, string Password, string Originator, string Recipients, string MessageData, string TokenReference, string TokenValidity, string TokenMask, string VerificationCode, string TokenCaseSensitive, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            object[] results = this.Invoke("SendTokenPhone", new object[] {
                        UserKey,
                        Password,
                        Originator,
                        Recipients,
                        MessageData,
                        TokenReference,
                        TokenValidity,
                        TokenMask,
                        VerificationCode,
                        TokenCaseSensitive,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTokenPhoneAsync(string UserKey, string Password, string Originator, string Recipients, string MessageData, string TokenReference, string TokenValidity, string TokenMask, string VerificationCode, string TokenCaseSensitive, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId) {
            this.SendTokenPhoneAsync(UserKey, Password, Originator, Recipients, MessageData, TokenReference, TokenValidity, TokenMask, VerificationCode, TokenCaseSensitive, URLBufferedMessageNotification, URLDeliveryNotification, URLNonDeliveryNotification, AffiliateId, null);
        }
        
        /// <remarks/>
        public void SendTokenPhoneAsync(string UserKey, string Password, string Originator, string Recipients, string MessageData, string TokenReference, string TokenValidity, string TokenMask, string VerificationCode, string TokenCaseSensitive, string URLBufferedMessageNotification, string URLDeliveryNotification, string URLNonDeliveryNotification, string AffiliateId, object userState) {
            if ((this.SendTokenPhoneOperationCompleted == null)) {
                this.SendTokenPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTokenPhoneOperationCompleted);
            }
            this.InvokeAsync("SendTokenPhone", new object[] {
                        UserKey,
                        Password,
                        Originator,
                        Recipients,
                        MessageData,
                        TokenReference,
                        TokenValidity,
                        TokenMask,
                        VerificationCode,
                        TokenCaseSensitive,
                        URLBufferedMessageNotification,
                        URLDeliveryNotification,
                        URLNonDeliveryNotification,
                        AffiliateId}, this.SendTokenPhoneOperationCompleted, userState);
        }
        
        private void OnSendTokenPhoneOperationCompleted(object arg) {
            if ((this.SendTokenPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTokenPhoneCompleted(this, new SendTokenPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/InquireDeliveryNotifications", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InquireDeliveryNotifications(string UserKey, string Password, string TransactionReferenceNumbers) {
            object[] results = this.Invoke("InquireDeliveryNotifications", new object[] {
                        UserKey,
                        Password,
                        TransactionReferenceNumbers});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InquireDeliveryNotificationsAsync(string UserKey, string Password, string TransactionReferenceNumbers) {
            this.InquireDeliveryNotificationsAsync(UserKey, Password, TransactionReferenceNumbers, null);
        }
        
        /// <remarks/>
        public void InquireDeliveryNotificationsAsync(string UserKey, string Password, string TransactionReferenceNumbers, object userState) {
            if ((this.InquireDeliveryNotificationsOperationCompleted == null)) {
                this.InquireDeliveryNotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInquireDeliveryNotificationsOperationCompleted);
            }
            this.InvokeAsync("InquireDeliveryNotifications", new object[] {
                        UserKey,
                        Password,
                        TransactionReferenceNumbers}, this.InquireDeliveryNotificationsOperationCompleted, userState);
        }
        
        private void OnInquireDeliveryNotificationsOperationCompleted(object arg) {
            if ((this.InquireDeliveryNotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InquireDeliveryNotificationsCompleted(this, new InquireDeliveryNotificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/RedeemVoucher", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RedeemVoucher(string UserKey, string Password, string RedeemCode) {
            object[] results = this.Invoke("RedeemVoucher", new object[] {
                        UserKey,
                        Password,
                        RedeemCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RedeemVoucherAsync(string UserKey, string Password, string RedeemCode) {
            this.RedeemVoucherAsync(UserKey, Password, RedeemCode, null);
        }
        
        /// <remarks/>
        public void RedeemVoucherAsync(string UserKey, string Password, string RedeemCode, object userState) {
            if ((this.RedeemVoucherOperationCompleted == null)) {
                this.RedeemVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRedeemVoucherOperationCompleted);
            }
            this.InvokeAsync("RedeemVoucher", new object[] {
                        UserKey,
                        Password,
                        RedeemCode}, this.RedeemVoucherOperationCompleted, userState);
        }
        
        private void OnRedeemVoucherOperationCompleted(object arg) {
            if ((this.RedeemVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RedeemVoucherCompleted(this, new RedeemVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/CreateVoucher", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateVoucher(string UserKey, string Password, string NumberOfVouchers, string AmountCreditsPerVoucher, string Remarks) {
            object[] results = this.Invoke("CreateVoucher", new object[] {
                        UserKey,
                        Password,
                        NumberOfVouchers,
                        AmountCreditsPerVoucher,
                        Remarks});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateVoucherAsync(string UserKey, string Password, string NumberOfVouchers, string AmountCreditsPerVoucher, string Remarks) {
            this.CreateVoucherAsync(UserKey, Password, NumberOfVouchers, AmountCreditsPerVoucher, Remarks, null);
        }
        
        /// <remarks/>
        public void CreateVoucherAsync(string UserKey, string Password, string NumberOfVouchers, string AmountCreditsPerVoucher, string Remarks, object userState) {
            if ((this.CreateVoucherOperationCompleted == null)) {
                this.CreateVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateVoucherOperationCompleted);
            }
            this.InvokeAsync("CreateVoucher", new object[] {
                        UserKey,
                        Password,
                        NumberOfVouchers,
                        AmountCreditsPerVoucher,
                        Remarks}, this.CreateVoucherOperationCompleted, userState);
        }
        
        private void OnCreateVoucherOperationCompleted(object arg) {
            if ((this.CreateVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateVoucherCompleted(this, new CreateVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/GetVoucherTransactions", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vouchers[] GetVoucherTransactions(string UserKey, string Password) {
            object[] results = this.Invoke("GetVoucherTransactions", new object[] {
                        UserKey,
                        Password});
            return ((vouchers[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVoucherTransactionsAsync(string UserKey, string Password) {
            this.GetVoucherTransactionsAsync(UserKey, Password, null);
        }
        
        /// <remarks/>
        public void GetVoucherTransactionsAsync(string UserKey, string Password, object userState) {
            if ((this.GetVoucherTransactionsOperationCompleted == null)) {
                this.GetVoucherTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVoucherTransactionsOperationCompleted);
            }
            this.InvokeAsync("GetVoucherTransactions", new object[] {
                        UserKey,
                        Password}, this.GetVoucherTransactionsOperationCompleted, userState);
        }
        
        private void OnGetVoucherTransactionsOperationCompleted(object arg) {
            if ((this.GetVoucherTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVoucherTransactionsCompleted(this, new GetVoucherTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/GetStatusCodeDescription", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStatusCodeDescription(string StatusCode) {
            object[] results = this.Invoke("GetStatusCodeDescription", new object[] {
                        StatusCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusCodeDescriptionAsync(string StatusCode) {
            this.GetStatusCodeDescriptionAsync(StatusCode, null);
        }
        
        /// <remarks/>
        public void GetStatusCodeDescriptionAsync(string StatusCode, object userState) {
            if ((this.GetStatusCodeDescriptionOperationCompleted == null)) {
                this.GetStatusCodeDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusCodeDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetStatusCodeDescription", new object[] {
                        StatusCode}, this.GetStatusCodeDescriptionOperationCompleted, userState);
        }
        
        private void OnGetStatusCodeDescriptionOperationCompleted(object arg) {
            if ((this.GetStatusCodeDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusCodeDescriptionCompleted(this, new GetStatusCodeDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.aspPhone.com/aspPhonex2.asmx/VersionInfo", RequestNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", ResponseNamespace="https://webservice.aspPhone.com/aspPhonex2.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VersionInfo() {
            object[] results = this.Invoke("VersionInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionInfoAsync() {
            this.VersionInfoAsync(null);
        }
        
        /// <remarks/>
        public void VersionInfoAsync(object userState) {
            if ((this.VersionInfoOperationCompleted == null)) {
                this.VersionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionInfoOperationCompleted);
            }
            this.InvokeAsync("VersionInfo", new object[0], this.VersionInfoOperationCompleted, userState);
        }
        
        private void OnVersionInfoOperationCompleted(object arg) {
            if ((this.VersionInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionInfoCompleted(this, new VersionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.aspPhone.com/aspPhonex2.asmx")]
    public partial class vouchers {
        
        private string voucherCodeField;
        
        private string remarkField;
        
        private string creditsField;
        
        private string createdField;
        
        private string redeemedField;
        
        /// <remarks/>
        public string VoucherCode {
            get {
                return this.voucherCodeField;
            }
            set {
                this.voucherCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string Credits {
            get {
                return this.creditsField;
            }
            set {
                this.creditsField = value;
            }
        }
        
        /// <remarks/>
        public string Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string Redeemed {
            get {
                return this.redeemedField;
            }
            set {
                this.redeemedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SimpleWAPPushCompletedEventHandler(object sender, SimpleWAPPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimpleWAPPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimpleWAPPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendSimpleTextPhoneCompletedEventHandler(object sender, SendSimpleTextPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSimpleTextPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSimpleTextPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendTextPhoneCompletedEventHandler(object sender, SendTextPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTextPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTextPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendUnicodePhoneCompletedEventHandler(object sender, SendUnicodePhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUnicodePhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUnicodePhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckCreditsCompletedEventHandler(object sender, CheckCreditsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCreditsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCreditsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendOriginatorUnlockCodeCompletedEventHandler(object sender, SendOriginatorUnlockCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOriginatorUnlockCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOriginatorUnlockCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UnlockOriginatorCompletedEventHandler(object sender, UnlockOriginatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnlockOriginatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnlockOriginatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckOriginatorAuthorizationCompletedEventHandler(object sender, CheckOriginatorAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckOriginatorAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckOriginatorAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerifyTokenCompletedEventHandler(object sender, VerifyTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendTokenPhoneCompletedEventHandler(object sender, SendTokenPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTokenPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTokenPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InquireDeliveryNotificationsCompletedEventHandler(object sender, InquireDeliveryNotificationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InquireDeliveryNotificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InquireDeliveryNotificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RedeemVoucherCompletedEventHandler(object sender, RedeemVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RedeemVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RedeemVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CreateVoucherCompletedEventHandler(object sender, CreateVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetVoucherTransactionsCompletedEventHandler(object sender, GetVoucherTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVoucherTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVoucherTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vouchers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vouchers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetStatusCodeDescriptionCompletedEventHandler(object sender, GetStatusCodeDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusCodeDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusCodeDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VersionInfoCompletedEventHandler(object sender, VersionInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591